/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Grupo 6
 */
public class BuscarEmpleados extends javax.swing.JFrame {

    Conexion cc=new Conexion();
    Connection con=cc.conexion();
    
    public BuscarEmpleados() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Buscar Empleados");
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtbuscarEmpleado = new javax.swing.JTextField();
        txtcodigoB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombreB = new javax.swing.JTextField();
        txtcargoB = new javax.swing.JTextField();
        txtdepartamentoB = new javax.swing.JTextField();
        txtfechaB = new javax.swing.JTextField();
        btncargardatos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Código Empleado:");

        txtbuscarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtbuscarEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtbuscarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtbuscarEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarEmpleadoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarEmpleadoKeyReleased(evt);
            }
        });

        txtcodigoB.setEditable(false);
        txtcodigoB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtcodigoB.setForeground(new java.awt.Color(255, 51, 51));
        txtcodigoB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Busqueda de datos del Empleado");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre Empleado:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cargo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Departamento:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Feche de ingreso:");

        txtnombreB.setEditable(false);
        txtnombreB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtnombreB.setForeground(new java.awt.Color(255, 51, 51));
        txtnombreB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtcargoB.setEditable(false);
        txtcargoB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtcargoB.setForeground(new java.awt.Color(255, 51, 51));
        txtcargoB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtdepartamentoB.setEditable(false);
        txtdepartamentoB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtdepartamentoB.setForeground(new java.awt.Color(255, 51, 51));
        txtdepartamentoB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtfechaB.setEditable(false);
        txtfechaB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtfechaB.setForeground(new java.awt.Color(255, 51, 51));
        txtfechaB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btncargardatos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncargardatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cargarDatos.png"))); // NOI18N
        btncargardatos.setText("Cargar datos");
        btncargardatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btncargardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargardatosActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Código:");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/copyrigh.png"))); // NOI18N
        jLabel9.setText("2021 HGGS TECHNOLOGY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtbuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(105, 105, 105))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcodigoB, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdepartamentoB, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombreB, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfechaB, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btncargardatos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcargoB, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtbuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodigoB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombreB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcargoB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdepartamentoB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtfechaB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btncargardatos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
      
       public void  filtrar(String codigo){
        
        
         String [] titulos  ={"ID","CODIGO EMPLEADO","NOMBRE EMPLEADO","DEPARTAMENTO","PLAZA","PUESTO","TIPO EMPLEADO","ESTADO","FECHA INGRESO"};
        String [] registros =new String[10];
        DefaultTableModel modelo= new DefaultTableModel(null, titulos);
        String SQL ="select * from empleados where codigo like '%"+codigo+"%'";

        try {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            
            while (rs.next()){

                registros [0]=rs.getString("idempleado");
                registros [1]=rs.getString("codigo");
                registros [2]=rs.getString("nombre");
                registros [3]=rs.getString("departamento");
                registros [4]=rs.getString("plaza");
                registros [5]=rs.getString("puesto");
                registros [6]=rs.getString("tipoempleado");
                registros [7]=rs.getString("estado");
                registros [8]=rs.getString("fechaingreso"); 
                
                modelo.addRow(registros);

            }
             //tbEmpleados.setModel(modelo);
         txtcodigoB.setText(registros[1]);   
         txtnombreB.setText(registros[2]);
         txtcargoB.setText(registros[5]);
         txtdepartamentoB.setText(registros[3]);
         txtfechaB.setText(registros[8]);
         


        }catch (Exception e){
          JOptionPane.showMessageDialog(null,"Error al mostrar datos" + e.getMessage());
          

        }
        
    }
    
    
    private void txtbuscarEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarEmpleadoKeyReleased
        // TODO add your handling code here:
        filtrar(txtbuscarEmpleado.getText());
        
    }//GEN-LAST:event_txtbuscarEmpleadoKeyReleased

    private void btncargardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargardatosActionPerformed
        // TODO add your handling code here:
        Carnet c = new  Carnet();
        c.setVisible(true);
        String codigo=txtcodigoB.getText();
        String nombre=txtnombreB.getText();
        String cargo=txtcargoB.getText();
        String departamento=txtdepartamentoB.getText();
        String fecha=txtfechaB.getText();

        Carnet.txtcodigoC.setText( codigo);
        Carnet.txtNombreC.setText(nombre);
        Carnet.txtcargoC.setText(cargo);
        Carnet.txtdepartamentoC.setText(departamento);
        Carnet.txtfechaIC.setText(fecha);
       
        this.dispose();
    }//GEN-LAST:event_btncargardatosActionPerformed

    
    
    private void txtbuscarEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarEmpleadoKeyPressed
        // TODO add your handling code here:
        
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             Carnet c = new  Carnet();
        c.setVisible(true);
        String codigo=txtcodigoB.getText();
        String nombre=txtnombreB.getText();
        String cargo=txtcargoB.getText();
        String departamento=txtdepartamentoB.getText();
        String fecha=txtfechaB.getText();

        Carnet.txtcodigoC.setText( codigo);
        Carnet.txtNombreC.setText(nombre);
        Carnet.txtcargoC.setText(cargo);
        Carnet.txtdepartamentoC.setText(departamento);
        Carnet.txtfechaIC.setText(fecha);
       
        this.dispose();
             
         }
    }//GEN-LAST:event_txtbuscarEmpleadoKeyPressed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncargardatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtbuscarEmpleado;
    private javax.swing.JTextField txtcargoB;
    private javax.swing.JTextField txtcodigoB;
    private javax.swing.JTextField txtdepartamentoB;
    private javax.swing.JTextField txtfechaB;
    private javax.swing.JTextField txtnombreB;
    // End of variables declaration//GEN-END:variables
}
