/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.File;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.*;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Grupo 6
 */
public class Carnet extends javax.swing.JFrame implements Printable {

    Conexion cc=new Conexion();
    //Connection con=cc.conexion();

    public Carnet() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setTitle("Creación del Carnet");
        this.getContentPane().setBackground(getBackground ());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel16 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        PanelCarnet = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcargoC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtdepartamentoC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtcodigoC = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jfoto = new javax.swing.JLabel();
        txtfechaIC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnregistroB = new javax.swing.JButton();
        txtbuscar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/copyrigh.png"))); // NOI18N
        jLabel16.setText("2021 HGGS TECNNOLOGY");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/impresora.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMPRIME(evt);
            }
        });

        PanelCarnet.setBackground(new java.awt.Color(255, 255, 255));
        PanelCarnet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CONAL, S.A de C.V");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel3.setText("CONFECCIONES CHALCHUAPA S.A de C.V");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel4.setText("Zona Franca 10 KM. 76 1/2 ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel5.setText("Bypass Chalchuapa Santa Ana");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel6.setText("Tels: 2489-3100, 2489-3104");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("Por la presente se hace constar que :");

        txtNombreC.setEditable(false);
        txtNombreC.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNombreC.setForeground(new java.awt.Color(153, 0, 0));
        txtNombreC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("Cargo:");

        txtcargoC.setEditable(false);
        txtcargoC.setBackground(new java.awt.Color(255, 255, 255));
        txtcargoC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtcargoC.setForeground(new java.awt.Color(153, 0, 0));
        txtcargoC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("Es empleado de esta empresa en el");

        txtdepartamentoC.setEditable(false);
        txtdepartamentoC.setBackground(new java.awt.Color(255, 255, 255));
        txtdepartamentoC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtdepartamentoC.setForeground(new java.awt.Color(153, 0, 0));
        txtdepartamentoC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("desde la fecha de :");

        txtcodigoC.setEditable(false);
        txtcodigoC.setBackground(new java.awt.Color(255, 255, 255));
        txtcodigoC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtcodigoC.setForeground(new java.awt.Color(153, 0, 0));
        txtcodigoC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtcodigoC.setCaretColor(new java.awt.Color(0, 0, 204));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("Firma del GERENTE");

        jfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtfechaIC.setEditable(false);
        txtfechaIC.setBackground(new java.awt.Color(255, 255, 255));
        txtfechaIC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtfechaIC.setForeground(new java.awt.Color(153, 0, 0));
        txtfechaIC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("depto. de:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel14.setText("El Salvador C.A.");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setText("CARNET DE IDENTIFICACIÓN");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/firma.png"))); // NOI18N

        javax.swing.GroupLayout PanelCarnetLayout = new javax.swing.GroupLayout(PanelCarnet);
        PanelCarnet.setLayout(PanelCarnetLayout);
        PanelCarnetLayout.setHorizontalGroup(
            PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCarnetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCarnetLayout.createSequentialGroup()
                        .addGroup(PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCarnetLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addGap(18, 18, 18)
                        .addComponent(txtcodigoC, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCarnetLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(84, 84, 84)
                        .addGroup(PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel14)))
                    .addGroup(PanelCarnetLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addGroup(PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(PanelCarnetLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtfechaIC))
                                .addGroup(PanelCarnetLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtdepartamentoC, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCarnetLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtcargoC, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                                .addComponent(txtNombreC)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCarnetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addGap(172, 172, 172))
        );
        PanelCarnetLayout.setVerticalGroup(
            PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCarnetLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addGroup(PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(9, 9, 9)
                .addGroup(PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodigoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(4, 4, 4)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCarnetLayout.createSequentialGroup()
                        .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtcargoC, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtdepartamentoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfechaIC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(jfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("CREACIÓN DE CARNET");

        btnregistroB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnregistroB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btnregistroB.setText("Registro");
        btnregistroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroBActionPerformed(evt);
            }
        });

        txtbuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar user.png"))); // NOI18N
        txtbuscar.setText("Buscar");
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar foto.png"))); // NOI18N
        jButton3.setText("Buscar foto de Empleado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/copyrigh.png"))); // NOI18N
        jLabel17.setText("2021 HGGS TECHNOLOGY");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 51));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carnet-de-identidad.png"))); // NOI18N
        jLabel18.setText("Version: 3.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(PanelCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnregistroB)
                            .addComponent(jLabel17))
                        .addGap(33, 33, 33)
                        .addComponent(txtbuscar)
                        .addGap(38, 38, 38)
                        .addComponent(btnImprimir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(PanelCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregistroB)
                    .addComponent(txtbuscar)
                    .addComponent(btnImprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    File archivo;
    
    private void btnregistroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroBActionPerformed
        // TODO add your handling code here:
        
        Registro verregistro = new Registro();
        verregistro.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnregistroBActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int resultado ;

        carnett Buscador = new carnett();

        FileNameExtensionFilter formato = new FileNameExtensionFilter ("JPG, PNG Y GIF","jpg","png","gif");

        Buscador.JFCIMG.setFileFilter(formato);

        resultado = Buscador.JFCIMG.showOpenDialog(null);

        if(JFileChooser.APPROVE_OPTION== resultado){

            archivo=Buscador.JFCIMG.getSelectedFile();
            //Jdireccion.setText(archivo.getAbsoluteFile());

            try {
                ImageIcon ImgIcon = new ImageIcon (archivo.toString());

                Icon icono=new ImageIcon(ImgIcon.getImage().getScaledInstance(jfoto.getWidth(),jfoto.getHeight(), Image.SCALE_AREA_AVERAGING));

                jfoto.setIcon(icono);

            }catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null,"Error al abrir"+ ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
        
       BuscarEmpleados verbuscarempleados = new BuscarEmpleados();
        
       verbuscarempleados.setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void IMPRIME(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMPRIME
        // TODO add your handling code here:
      try 
      {
          PrinterJob job =PrinterJob.getPrinterJob();
          job.setPrintable(this);
        boolean ok = job.printDialog();
        
        if(ok)
        {
         job.print();
              this.dispose();
        
        }
        Registro verregistro = new Registro();
        verregistro.setVisible(true);
        this.dispose();
        
          
      } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, "Error de programa","Error\n"+ex,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_IMPRIME
    
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carnet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel PanelCarnet;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnregistroB;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    public static javax.swing.JLabel jfoto;
    public static javax.swing.JTextField txtNombreC;
    private javax.swing.JButton txtbuscar;
    public static javax.swing.JTextField txtcargoC;
    public static javax.swing.JTextField txtcodigoC;
    protected static javax.swing.JTextField txtdepartamentoC;
    public static javax.swing.JTextField txtfechaIC;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int Index) throws PrinterException {
        
        if (Index>0)
        {
            
            return NO_SUCH_PAGE;
        }
        Graphics2D hub=(Graphics2D)graf;
        hub.translate(pagfor.getImageableX()+30,pagfor.getImageableY()+30);
        hub.scale(1.0,1.0);
        
        PanelCarnet.printAll(graf);
        return PAGE_EXISTS;
        
    }
}
