/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;


import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Grupo 6
 */
public class Registro extends javax.swing.JFrame {
    
    Conexion cc=new Conexion();
    Connection con=cc.conexion();

    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Registro de empleados");
        this.getContentPane().setBackground(getBackground ());
        mostrardatos();
        limpiar();
        txtcodigo.requestFocus();
        
        
        
        TableColumn columna;
      columna=tbEmpleados.getColumnModel().getColumn(5);
      
      columna.setPreferredWidth(70);
      columna.setMaxWidth(70);
      columna.setMinWidth(70);
         
      tbEmpleados.setRowHeight(20);
      tbEmpleados.setBackground(Color.white);
      
       tbEmpleados.setRowHeight(20);
tbEmpleados.getColumnModel().getColumn(0).setPreferredWidth(5); //ID
tbEmpleados.getColumnModel().getColumn(1).setPreferredWidth(80);
tbEmpleados.getColumnModel().getColumn(2).setPreferredWidth(210);//nombre
tbEmpleados.getColumnModel().getColumn(3).setPreferredWidth(40);//departamento
tbEmpleados.getColumnModel().getColumn(4).setPreferredWidth(90);
tbEmpleados.getColumnModel().getColumn(6).setPreferredWidth(45);//tipo
tbEmpleados.getColumnModel().getColumn(7).setPreferredWidth(10); //estado
tbEmpleados.getColumnModel().getColumn(8).setPreferredWidth(40);
//tbEmpleados.getColumnModel().getColumn(9).setPreferredWidth(60);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        cbodepartamento = new javax.swing.JComboBox<>();
        cboplaza = new javax.swing.JComboBox<>();
        cbotipoempleado = new javax.swing.JComboBox<>();
        cboestado = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbopuesto = new javax.swing.JComboBox<>();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btncrear = new javax.swing.JButton();
        jdfecha = new com.toedter.calendar.JDateChooser();
        txtcodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpleados = new javax.swing.JTable();
        btnResRes = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        btnordenar = new javax.swing.JButton();
        btnacercade = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Código Empleado:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nombre Empleado:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Fecha de Ingreso:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Departamento:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Plaza:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tipo de empleado:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Estado:");

        txtnombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        cbodepartamento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbodepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producción", "Supervisor", "Mantenimiento", "Bodega de Telas", "Calidad", "Embarque", "Corte", "Entrenamiento", "Recursos Humanos", "Control de Producción", "Muestras", "Oficina", "Bodega de Accesorios", "Persona que da mantenimiento", "Pasamateriales", "Limpieza", "Gerencia", "A37001-L001", "A37002-L001", "A37002-L002", "A37002-L003", "A37002-L004", "A37002-L005", "A37002-L006", "A37002-L007", "A37002-L008", "A37002-L009", "A37003-L001", "A37004-L001" }));
        cbodepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbodepartamentoActionPerformed(evt);
            }
        });

        cboplaza.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboplaza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IMPORTACIÓN", "Supervisor de Costura ", "Mecánico I", "Mecánico II", "Supervisor de bodega de telas", "Asistente de bodega de telas", "Inspector Control de Calidad", "Auxiliar de Embarque", "Asistente de Corte", "Entrenador", "Asistente de Recursos Humanos", "Auditor Control de Calidad", "Asistente de Control de Producción", "Supervisor de Muestras", "Supervisor de Entrenamiento", "Asistente de cuentas por cobrar", "Inspector de muestras", "Auxiliar de Embarque", "Asistente de Sistema de Inventario", "Asistente de Bodega de Accesorios", "Auxiliar de Enfermeria", "Asistente de Planilla", "Persona que da mantenimiento", "Clasificador de Irregulares", "Cerrador de corte", "Supervisor de Embarque", "Recepcionista / Asistente", "Asistente de corte / Plotter", "Supervisor de Control de Calidad", "Supervisor de Empaque", "Pasamaterial de Costura", "Pasamaterial de Empaque", "Reciclador de materia prima", "Enfermera", "Gerente de oficina", "Gerente Control de Producción", "Gerente de Corte", "Gerente de Planta", "Gerente de Recursos Humanos", "Gerente de Producción", "Limpieza", "Doctor de planta", "Jefe de Linea", "A", "A+", "B", "C" }));

        cbotipoempleado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbotipoempleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Directo", "Indirecto" }));

        cboestado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cboestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboestadoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Puesto:");

        cbopuesto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbopuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operario", "Gerente de Producción", "Supervisor de Costura", "Supervisor de bodega de telas", "Inspector Control de Calidad", "Asistente de Embarque", "Mecánico I", "Auditor Control de Calidad", "Asistente de Corte", "Entrenadores", "Asistente Recursos Humanos", "Asistente Control de Producción", "Supervisor de Muestras", "Supervisor de Entrenamiento", "Asistente de Cuentas por Pagar", "Inspector de Muestras", "Asistente de Sistema de Inventario", "Asistente de Bodega de Accesorios", "Auxiliar de Enfermeria", "Asistente de Planillas", "Persona que da mantenimiento", "Clasificador de Irregulares", "Recepcionista", "Mecánico II", "Asistente de Corte / Plotter", "Pasamaterial de Costura", "Asistente de Bodega de Telas", "Supervisor de Empaque", "Cerrador de Corte", "Pasamaterial de Empaque", "Reciclador de Materia Prima de Producción", "Enfermera", "Gerente de Oficina", "Gerente Control de Producción", "Gerente de Corte", "Gerente de Recursos Humanos", "Gerente de Planta", "Jefé de Linea", "Doctor en Planta" }));

        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnguardar.setText("Guardar Registro");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnactualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        btnactualizar.setText("Actualizar Registro");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminarD.png"))); // NOI18N
        btneliminar.setText("Eliminar Registro");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnnuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        btnnuevo.setText("Nuevo Registro");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btncrear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crear.png"))); // NOI18N
        btncrear.setText("Craear carnet");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        jdfecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jdfecha.setDateFormatString("yyyy/MM/dd\n");
        jdfecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdfecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdfechaKeyPressed(evt);
            }
        });

        txtcodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoKeyTyped(evt);
            }
        });

        tbEmpleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        tbEmpleados.setToolTipText("");
        tbEmpleados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tbEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEmpleados);

        btnResRes.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnResRes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/base.png"))); // NOI18N
        btnResRes.setText("Respaldo y Restauración");
        btnResRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResResActionPerformed(evt);
            }
        });

        btncerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        btncerrar.setText("Login");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        btnordenar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnordenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flechas.png"))); // NOI18N
        btnordenar.setText("Ordenar Tabla");
        btnordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordenarActionPerformed(evt);
            }
        });

        btnacercade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnacercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/acerca-de.png"))); // NOI18N
        btnacercade.setText("Acerca de Nosotros");
        btnacercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacercadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnResRes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnacercade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel6)))
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbopuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnordenar))
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbodepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboplaza, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbotipoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboestado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnordenar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbodepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboplaza, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbopuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbotipoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cboestado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jdfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResRes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnacercade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE EMPLEADOS");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Datos del empleado");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        jLabel15.setText("Buscar Empleado:");

        txtbuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 51));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carnet-de-identidad.png"))); // NOI18N
        jLabel17.setText("Version: 3.0");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/copyrigh.png"))); // NOI18N
        jLabel18.setText("2021 HGGS TECNNOLOGY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(1699, 1699, 1699))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(61, 61, 61))))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel17)))
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void  mostrardatos(){
        
        
         String [] titulos  ={"ID","CODIGO EMPLEADO","NOMBRE EMPLEADO","DEPARTAMENTO","PLAZA","PUESTO","TIPO EMPLEADO","ESTADO","FECHA INGRESO"};
        String [] registros =new String[10];
        DefaultTableModel modelo= new DefaultTableModel(null, titulos);
        String SQL ="select * from empleados";

        try {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            
            while (rs.next()){

                registros [0]=rs.getString("idempleado");
                registros [1]=rs.getString("codigo");
                registros [2]=rs.getString("nombre");
                registros [3]=rs.getString("departamento");
                registros [4]=rs.getString("plaza");
                registros [5]=rs.getString("puesto");
                registros [6]=rs.getString("tipoempleado");
                registros [7]=rs.getString("estado");
                registros [8]=rs.getString("fechaingreso"); 
                
                modelo.addRow(registros);
              //jTextField1.setText(registros[2]);

            }
           tbEmpleados.setModel(modelo);
         

        }catch (Exception e){
          JOptionPane.showMessageDialog(null,"Error al mostrar datos" + e.getMessage());
        }
    }
   
      public void  filtrardatos(String codigo){
        
        
         String [] titulos  ={"ID","CODIGO EMPLEADO","NOMBRE EMPLEADO","DEPARTAMENTO","PLAZA","PUESTO","TIPO EMPLEADO","ESTADO","FECHA INGRESO"};
        String [] registros =new String[10];
        DefaultTableModel modelo= new DefaultTableModel(null, titulos);
        String SQL ="select * from empleados where codigo like '%"+codigo+"%'";

        try {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            
            while (rs.next()){

                registros [0]=rs.getString("idempleado");
                registros [1]=rs.getString("codigo");
                registros [2]=rs.getString("nombre");
                registros [3]=rs.getString("departamento");
                registros [4]=rs.getString("plaza");
                registros [5]=rs.getString("puesto");
                registros [6]=rs.getString("tipoempleado");
                registros [7]=rs.getString("estado");
                registros [8]=rs.getString("fechaingreso"); 
                
                modelo.addRow(registros);
                 if(tbEmpleados.getSelectedRowCount()>0){
               
           }
         

            }
           tbEmpleados.setModel(modelo);
            
        }catch (Exception e){
          JOptionPane.showMessageDialog(null,"Error al mostrar datos" + e.getMessage());

        }
        
    }
    public void limpiar (){
        txtcodigo.setText("");
        txtnombre.setText("");
        cbodepartamento.setSelectedItem(null);
        cboplaza.setSelectedItem(null);
        cbopuesto.setSelectedItem(null);     
        cbotipoempleado.setSelectedItem(null);
        cboestado.setSelectedItem(null);
        jdfecha.setDate(null);
                
    }
    
    public  void  insertarEmpleados()
    {
        try {
           
   
           int codigo =Integer.parseInt(txtcodigo.getText());
           String nombre = txtnombre.getText();
           int departamentoS =cbodepartamento.getSelectedIndex();
           int plazaS =cboplaza.getSelectedIndex();           
           int puestoS =cbopuesto.getSelectedIndex();
           int tipoS =cbotipoempleado.getSelectedIndex();
           int estadoS =cboestado.getSelectedIndex();
       
           String SQL = "insert into empleados (codigo,nombre,departamento,plaza,puesto,tipoempleado,estado,fechaingreso) values (?,?,?,?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(SQL);
            pst.setInt(1, codigo);
            pst.setString(2, nombre);
            pst.setString(3, cbodepartamento.getItemAt(departamentoS));
            pst.setString(4, cboplaza.getItemAt(plazaS));
            pst.setString(5, cbopuesto.getItemAt(puestoS));
            pst.setString(6, cbotipoempleado.getItemAt(tipoS));
            pst.setString(7, cboestado.getItemAt(estadoS));
            pst.setString(8, ((JTextField)jdfecha.getDateEditor().getUiComponent()).getText());
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Registro alamecenado correctamente ");
           txtcodigo.requestFocus();
        }catch (Exception e){
            
            JOptionPane.showMessageDialog(null,"Error de Registro" + e.getMessage());
        }
    }
    
    public  void  ActualizarEmpleados()
    {
        try {
   
           int codigo =Integer.parseInt(txtcodigo.getText());
           String nombre = txtnombre.getText();
           int departamentoS =cbodepartamento.getSelectedIndex();
           int plazaS =cboplaza.getSelectedIndex();           
           int puestoS =cbopuesto.getSelectedIndex();
           int tipoS =cbotipoempleado.getSelectedIndex();
           int estadoS =cboestado.getSelectedIndex();
       
           String SQL = "update empleados set codigo=?,nombre=?,departamento=?,plaza=?,puesto=?,tipoempleado=?,estado=?,fechaingreso=? where idempleado=?";
            PreparedStatement pst=con.prepareStatement(SQL);
            
            
            int filaseleccionada = tbEmpleados.getSelectedRow();
            String H= (String)tbEmpleados.getValueAt(filaseleccionada, 0);
            pst.setInt(1, codigo);
            pst.setString(2, nombre);
            pst.setString(3, cbodepartamento.getItemAt(departamentoS));
            pst.setString(4, cboplaza.getItemAt(plazaS));
            pst.setString(5, cbopuesto.getItemAt(puestoS));
            pst.setString(6, cbotipoempleado.getItemAt(tipoS));
            pst.setString(7, cboestado.getItemAt(estadoS));
            pst.setString(8, ((JTextField)jdfecha.getDateEditor().getUiComponent()).getText());
            
            pst.setString(9, H);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Resistro Actualizado");

        }catch (Exception e){
            
            JOptionPane.showMessageDialog(null,"Error de Actualización" + e.getMessage());
        }
    }
    
    public  void EliminarEmpleados()
    {   
        int filaseleccionada=tbEmpleados.getSelectedRow();
                            try {
                                
                                String SQl="delete from empleados where idempleado="+tbEmpleados.getValueAt(filaseleccionada,0);
                                Statement st = con.createStatement();
                                int n=st.executeUpdate(SQl);
                                if (n>=0){
                                    JOptionPane.showMessageDialog(null,"Resistro Eliminado");
                             }
                       
                    }catch (Exception e){
                        JOptionPane.showMessageDialog(null,"Error al Eliminar Registro" + e.getMessage());
                    }

    }
    
    
    
    
         public void cerrar(){
 Object [] opciones ={"Aceptar","Cancelar"};
 int eleccion = JOptionPane.showOptionDialog(rootPane,"En relidad desea cerrar el programa","Mensaje de Confirmacion",
 JOptionPane.YES_NO_OPTION,
 JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
 if (eleccion == JOptionPane.YES_OPTION)
 {
 System.exit(0);
 }else{
 }
     }
    
    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        // TODO add your handling code here:

        filtrardatos(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void txtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyTyped

        //Validar que solo acepte numeros
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Solo se permiten números");
        }
    }//GEN-LAST:event_txtcodigoKeyTyped

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        // Abrir el formulario del carnet

        Carnet vercarnet = new Carnet();
        vercarnet.setVisible(true);
        this.dispose();
       
      

    }//GEN-LAST:event_btncrearActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:

        limpiar();
        txtcodigo.requestFocus();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        EliminarEmpleados();

        mostrardatos();
        limpiar();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:

        ActualizarEmpleados();
        mostrardatos();
        limpiar();
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        if (txtcodigo.getText().isEmpty()||txtnombre.getText().isEmpty()||cbodepartamento.getSelectedItem().toString().isEmpty()
            ||cboplaza.getSelectedItem().toString().isEmpty()||cbopuesto.getSelectedItem().toString().isEmpty()
            ||cbotipoempleado.getSelectedItem().toString().isEmpty()
            ||cboestado.getSelectedItem().toString().isEmpty()){
            if(jdfecha.getDate()==null){
                JOptionPane.showMessageDialog(null, "El campo fecha esta vacio","Atención!!",JOptionPane.OK_OPTION);
                return;
            }
            JOptionPane.showMessageDialog(null,"Error de almacenamiento de usuario ");
        }else{
            insertarEmpleados();
            limpiar();
            mostrardatos();
            //JOptionPane.showMessageDialog(null,"Registro alamecenado correctamente ");

        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void cboestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboestadoActionPerformed

    private void cbodepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbodepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbodepartamentoActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        //Validar que solo acepte letras
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Solo se permiten letras");
        }

    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnResResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResResActionPerformed
        // TODO add your handling code here:
        ResRes verResRes = new ResRes();
        verResRes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnResResActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
    Login verLogin = new Login();
    verLogin.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btnordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordenarActionPerformed
        // TODO add your handling code here:
        
              tbEmpleados.setRowHeight(20);
tbEmpleados.getColumnModel().getColumn(0).setPreferredWidth(5); //ID
tbEmpleados.getColumnModel().getColumn(1).setPreferredWidth(80);
tbEmpleados.getColumnModel().getColumn(2).setPreferredWidth(200);//nombre
tbEmpleados.getColumnModel().getColumn(3).setPreferredWidth(40);//departamento
tbEmpleados.getColumnModel().getColumn(4).setPreferredWidth(90);
tbEmpleados.getColumnModel().getColumn(6).setPreferredWidth(45);//tipo
tbEmpleados.getColumnModel().getColumn(7).setPreferredWidth(-5); //estado
tbEmpleados.getColumnModel().getColumn(8).setPreferredWidth(40);
//tbEmpleados.getColumnModel().getColumn(9).setPreferredWidth(60);
    }//GEN-LAST:event_btnordenarActionPerformed

    private void tbEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEmpleadosMouseClicked
        // TODO add your handling code here:

        int filaseleccionada=tbEmpleados.rowAtPoint(evt.getPoint());
        txtcodigo.setText(tbEmpleados.getValueAt(filaseleccionada,1).toString());
        txtnombre.setText(tbEmpleados.getValueAt(filaseleccionada,2).toString());
        cbodepartamento.setSelectedItem(tbEmpleados.getValueAt(filaseleccionada,3));
        cboplaza.setSelectedItem(tbEmpleados.getValueAt(filaseleccionada,4));
        cbopuesto.setSelectedItem(tbEmpleados.getValueAt(filaseleccionada,5));
        cbotipoempleado.setSelectedItem(tbEmpleados.getValueAt(filaseleccionada,6));
        cboestado.setSelectedItem(tbEmpleados.getValueAt(filaseleccionada,7));
        jdfecha.setDateFormatString((String) tbEmpleados.getValueAt(filaseleccionada,8));
    }//GEN-LAST:event_tbEmpleadosMouseClicked

    private void btnacercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacercadeActionPerformed
        // TODO add your handling code here:
        
       Acercade veracercade = new Acercade();
       veracercade.setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_btnacercadeActionPerformed

    
    
    
    private void jdfechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdfechaKeyPressed
        // TODO add your handling code here:
             if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                 
                  if (txtcodigo.getText().isEmpty()||txtnombre.getText().isEmpty()||cbodepartamento.getSelectedItem().toString().isEmpty()
            ||cboplaza.getSelectedItem().toString().isEmpty()||cbopuesto.getSelectedItem().toString().isEmpty()
            ||cbotipoempleado.getSelectedItem().toString().isEmpty()
            ||cboestado.getSelectedItem().toString().isEmpty()){
            if(jdfecha.getDate()==null){
                JOptionPane.showMessageDialog(null, "El campo fecha esta vacio","Atención!!",JOptionPane.OK_OPTION);
                return;
            }
            JOptionPane.showMessageDialog(null,"Error de almacenamiento de usuario ");
        }else{
            insertarEmpleados();
            limpiar();
            mostrardatos();
            //JOptionPane.showMessageDialog(null,"Registro alamecenado correctamente ");

        }
             
    }//GEN-LAST:event_jdfechaKeyPressed
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnResRes;
    private javax.swing.JButton btnacercade;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnordenar;
    private javax.swing.JComboBox<String> cbodepartamento;
    private javax.swing.JComboBox<String> cboestado;
    private javax.swing.JComboBox<String> cboplaza;
    private javax.swing.JComboBox<String> cbopuesto;
    private javax.swing.JComboBox<String> cbotipoempleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdfecha;
    private javax.swing.JTable tbEmpleados;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
