/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Respaldo.respaldo;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Grupo 6
 */
public class ResRes extends javax.swing.JFrame {

    /**
     * Creates new form ResRes
     */
    public ResRes() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setTitle("Respaldo y Restauración");
        this.getContentPane().setBackground(getBackground ());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnrestauracion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnatras = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/respaldo.png"))); // NOI18N
        jButton1.setText("Respaldo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnrestauracion.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnrestauracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/restaurar.png"))); // NOI18N
        btnrestauracion.setText("Restauración");
        btnrestauracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestauracionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Respaldo y Restauración \"Base de Datos\"");

        btnatras.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        btnatras.setText("Registro de Empleados");
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/copyrigh.png"))); // NOI18N
        jLabel17.setText("2021 HGGS TECNNOLOGY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnatras)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(jButton1)
                            .addGap(18, 18, 18)
                            .addComponent(btnrestauracion)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnrestauracion))
                .addGap(33, 33, 33)
                .addComponent(btnatras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
        // TODO add your handling code here:
           Registro verregistro = new Registro();
        verregistro.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnatrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            Process p= Runtime.getRuntime().exec("C:\\xampp\\mysql\\bin\\mysqldump -u root -proot conalgaran37");
            InputStream is = p.getInputStream();
            FileOutputStream fos =new FileOutputStream("backup_conalgaran37.sql");
            
            byte [] buffer = new byte [1000];
            int leido = is.read(buffer);
            while(leido>0)
                
            {
                
                fos.write(buffer,0,leido);
                leido=is.read(buffer);
                
            }
            JOptionPane.showMessageDialog(null,"Respaldo realizado con éxito ");
            fos.close();
            
            
        } catch(IOException ex){
            Logger.getLogger(respaldo.class.getName()).log(Level.SEVERE, null, ex);
            
            
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnrestauracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestauracionActionPerformed
         // TODO add your handling code here:
        
           
        try {
            Process p= Runtime.getRuntime().exec(" mysql -u root -proot conalgaran37");
            OutputStream os = p.getOutputStream();
            FileInputStream fis =new FileInputStream("backup_conalgaran37.sql");
            
            byte [] buffer = new byte [1000];
            int leido = fis.read(buffer);
            while(leido>0)
                
            {
                
                os.write(buffer,0,leido);
                leido=fis.read(buffer);
                 
            }
            JOptionPane.showMessageDialog(null,"Restauracion realizada con éxito ");
                
            os.flush();
            os.close();
            fis.close();
            
            
        } catch(IOException ex){
            Logger.getLogger(respaldo.class.getName()).log(Level.SEVERE, null, ex);
            
            
            
        }
    }//GEN-LAST:event_btnrestauracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResRes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatras;
    private javax.swing.JButton btnrestauracion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    // End of variables declaration//GEN-END:variables
}
